name: check
on: push
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Installing dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        make install
        make configure
    - name: Linting by flake8
      run: make lint
    - name: Testing by pytest
      run: make test
